### ISSUE TITLE
[Bug]: Initializing Agent gets stuck in initial run

### ISSUE THREAD

**Issue by garyfeng** [garyfeng/OpenDevin#3]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

First time running, the WebUI either get stuck at the initializing agent stage, or anything you typed in the chat resulting in a vague error message

### Current OpenDevin version

```bash
v0.8 via docker.
```

### Installation and Configuration

```bash
docker setup, selected the LLM via the web interface as "Azure/GPT4o"
```

### Model and Agent

- Model: GPT4o
- Agent: CodeAct Agent

## OpenDevin stuck at initializing agent
Running into https://github.com/OpenDevin/OpenDevin/issues/3194

```sh
docker run -it \
    --env-file .env \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /Users/gfeng/.rd/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:0.8
```

which generates errors on UI

```
Error creating controller. Please check Docker is running and visit `https://docs.all-hands.dev/modules/usage/troubleshooting` for more debugging information..
```
in terminal:

```
session.py:116 - Error creating controller: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 398, in request
    self.endheaders()
  File "/usr/local/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/app/.venv/lib/python3.12/site-packages/docker/transport/unixconn.py", line 26, in connect
    sock.connect(self.unix_socket)
ConnectionRefusedError: [Errno 111] Connection refused
```

### Solution: reverted to the original docker command
And make sure we start a new session. This solved the problem. Agents seemed to have been initiated. We see a chatbot ready to talk.

## No Files in Workspace issue
But when I type anything, it pops an error message saying something like "no files in workspace". And the agent responds with "There was an unexpected error while running the agent".

In terminal:

```
02:37:42 - opendevin:INFO: browser_env.py:121 - Browser env started.
02:41:53 - USER_ACTION
**MessageAction** (source=EventSource.USER)
CONTENT: write a python function that generates the first 100 prime numbers. It should return a list containing the 100 prime numbers in order
INFO:     172.17.0.1:42550 - "GET /api/list-files?path=%2F HTTP/1.1" 200 OK


==============
CodeActAgent LEVEL 0 LOCAL STEP 0 GLOBAL STEP 0


Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/azure.py", line 651, in completion
    response = azure_client.chat.completions.create(**data, timeout=timeout)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 646, in create
    return self._post(
           ^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1266, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 942, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1046, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}
```

The error message seems to have to do with openAI not avaialble. Suspecting the `.env` file is not working. Try to use env variables directly:

```sh
docker run -it \
    -e LLM_BASE_URL="https://xxxx.openai.azure.com/" \
    -e LLM_API_KEY="XXXX" \
    -e LLM_MODEL="xxxgpt4o" \
    -e LLM_API_VERSION="2024-02-01" \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:0.8
```

but looking at the startup message, it looks like a problem with the `workspace` permission issue. 

```
03:09:02 - opendevin:INFO: agent.py:79 - Using runtime: server
03:09:02 - opendevin:INFO: ssh_box.py:135 - SSHBox is running as opendevin user with USER_ID=503 in the sandbox
03:09:02 - opendevin:INFO: ssh_box.py:178 - Detected initial session.
03:09:02 - opendevin:INFO: ssh_box.py:180 - Creating new Docker container
03:09:02 - opendevin:WARNING: ssh_box.py:578 - Using port forwarding till the enable host network mode of Docker is out of experimental mode.Check the 897th issue on https://github.com/OpenDevin/OpenDevin/issues/ for more information.
03:09:02 - opendevin:INFO: ssh_box.py:586 - Mounting volumes: {'/Users/gfeng/Documents/GitHub/opendevin/workspace': {'bind': '/workspace', 'mode': 'rw'}, '/tmp/cache': {'bind': '/home/opendevin/.cache', 'mode': 'rw'}}
03:09:02 - opendevin:INFO: ssh_box.py:597 - Container started
03:09:03 - opendevin:INFO: ssh_box.py:613 - waiting for container to start: 1, container status: running
03:09:05 - opendevin:WARNING: ssh_box.py:308 - Failed to chown workspace directory for opendevin in sandbox: b"chown: changing ownership of '/workspace': Permission denied\n". But this should be fine if the self.sandbox_workspace_dir='/workspace' is mounted by the app docker container.
03:09:06 - opendevin:INFO: ssh_box.py:342 - Connecting to SSH session...
03:09:06 - opendevin:INFO: ssh_box.py:345 - You can debug the SSH connection by running: `ssh -v -p 40867 opendevin@localhost` using the password '9e4fdc54-3181-4ee3-bd5c-1aa837cc9788'
03:09:07 - opendevin:INFO: ssh_box.py:349 - Connected to SSH session
03:09:10 - opendevin:INFO: agent.py:100 - Creating agent CodeActAgent using LLM azure/gpt-4o
03:09:10 - opendevin:INFO: mixin.py:42 - Initializing plugins in the sandbox
03:09:10 - opendevin:INFO: mixin.py:30 - Sourced /opendevin/bash.bashrc and ~/.bashrc successfully
03:09:10 - opendevin:INFO: mixin.py:59 - Copied files from [/app/opendevin/runtime/plugins/agent_skills] to [/opendevin/plugins/agent_skills] inside sandbox.
03:09:10 - opendevin:INFO: mixin.py:67 - Initializing plugin [agent_skills] by executing [/opendevin/plugins/agent_skills/setup.sh] in the sandbox.
```

See https://github.com/OpenDevin/OpenDevin/issues/2861, where a commenter suggests the `no file in workspace` is just an annoyance, but the real issue was the OpenAI.

So I created a `ignore.me` file with `haha` as the content. It fixed the "no file in workspace" but. The OpenAI error remains.

Now looking at https://github.com/OpenDevin/OpenDevin/issues/1187, it is possible that the `LLM_MODEL` parameter needs to be prefixed with `azure/`

```sh
docker run -it \
    -e LLM_BASE_URL="https://xxx.openai.azure.com/" \
    -e LLM_MODEL="azure/xxx-gpt4o" \
    -e LLM_API_VERSION="2024-02-01" \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:0.8
```

With the above command, we get a different error:

```
File "/app/.venv/lib/python3.12/site-packages/litellm/llms/azure.py", line 673, in completion
    raise AzureOpenAIError(status_code=e.status_code, message=str(e))
litellm.llms.azure.AzureOpenAIError: Error code: 404 - {'error': {'code': 'DeploymentNotFound', 'message': 'The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.'}}
```

### solution
1. Do not use quotations in `-e` or `.env`
2. Add `azure/` to the LLM deployment name as prefix
3. Need to set the LLM in the WebUI to exactly the same as the one in the `.env` file

**Comment by garyfeng** [comment]
To start, run the following command. Tested on MacOS, Rancher Desktop

```sh
WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --env-file .env \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:0.8
```

Here is the `.env` setup:

```
LLM_BASE_URL=https://********-northcentralus.openai.azure.com/
LLM_API_KEY=6b**************************37
LLM_MODEL=azure/******-gpt4o
LLM_API_VERSION=2024-02-01
```

In the UI to set up the Agent and LLM, 
- choose the `CodeAct Agent`
- for LLM, type `azure/aidev-gpt4o` or whatever is set up in your `.env` file. Notice:
  1. you must use `azure/DeployName`
  2. you must type (not choose) the exact same in the OpenDevin UI
  3. do not use quotation in your `.env` configuration
